feat: add blueprint scaffold
TheOpenForest/multisig-contract-v2 pull request #4
Opened 2024-10-28 06:05 UTC by allen-hsu

## JIRA ticket:

## What's new?

1. add blueprint scaffold feature

## New Findings

## Screenshots
![截圖 2024-10-28 下午2 04 55](https://github.com/user-attachments/assets/03f6ffd4-7562-484a-ad5a-627db1f3af22)

## References
https://github.com/1IxI1/blueprint-scaffold

## Notes

2024-10-28 08:10 UTC, RainBoltz requested changes
build passed, it works.

2024-10-28 08:14 UTC, thewildanimal requested changes

2024-10-28 08:14 UTC, thewildanimal commented on scaffold-plugin/dapp/.env
.env 是不是應該用 .env.example 然後把 .env 加進 .gitignore？

2024-10-29 03:09 UTC, allen-hsu commented on scaffold-plugin/dapp/.env
好的 我等等改一下

2024-10-29 05:36 UTC, allen-hsu commented on scaffold-plugin/dapp/.env
誒，不對，我應該要把整個 dapp ignore 掉會比較好，因為這些都是可以生產被部署的

2024-10-29 05:38 UTC, allen-hsu commented on scaffold-plugin/dapp/.env
那個 dist 那邊之後會用套件，現在是因為我的 PR 發布還沒被 approve，所以不能用他們的 npm 版本

2024-10-29 07:35 UTC, thewildanimal approved these changes
noticed, lgtm

2024-10-29 07:47 UTC, qbtf approved these changes
LGTM

Backlog: we committed scaffold's built result into repo. Maybe next time we can consider `patch-package` or yarn's own patching mechanism.

2024-10-29 07:49 UTC, merged